config/routes.rb
Rails.application.routes.draw do
  resources :flights, only: [ :index ]
  resources :bookings, only: [ :new, :create, :show ]
  root "flights#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/airport.rb
class Airport < ApplicationRecord
  validates :code, presence: true

  has_many :departing_flights, class_name: "Flight", foreign_key: "departure_airport_id"
  has_many :arriving_flights, class_name: "Flight", foreign_key: "arrival_airport_id"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  has_and_belongs_to_many :passengers
  has_and_belongs_to_many :flights

  accepts_nested_attributes_for :passengers, allow_destroy: true
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :departure_airport, class_name: "Airport"
  belongs_to :arrival_airport, class_name: "Airport"

  has_and_belongs_to_many :bookings

  before_validation :set_number

  validates_associated :departure_airport, :arrival_airport
  validates :duration, :start, :number, presence: true

  validates :duration, numericality: { greater_than: 0 }

  # Returns the details for the flight
  def details
    "#{departure_airport.code} ~> #{arrival_airport.code}"
  end

  # Returns the duration of the flight in hours and minutes
  def duration_in_hours
    hours = duration / 3600
    "#{hours}h"
  end

  private

  def set_number
    self.number ||= Faker::Number.unique.number(digits: 10)
  end
end

app/models/passenger.rb
class Passenger < ApplicationRecord
  has_and_belongs_to_many :bookings

  validates :name, :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_flight, only: [ :new ]
  before_action :set_booking, only: [ :show ]

  def new
    @booking = Booking.new
    @booking.flights << @flight
    @searched_query = {
      departure_airport: @flight.departure_airport.code,
      arrival_airport: @flight.arrival_airport.code,
      start: @flight.start,
      num_tickets: params[:num_tickets]
    }

    params[:num_tickets].to_i.times { @booking.passengers.build }
  end

  def create
    booking_params_without_flight = booking_params
    @flight = Flight.find(booking_params_without_flight.delete(:flight))
    @booking = Booking.new(booking_params_without_flight)
    @booking.flights << @flight

    if @booking.save
      @booking.passengers.each do |passenger|
        PassengerMailer
          .with(passenger: passenger, booking: @booking)
          .confirm
          .deliver_later
      end

      redirect_to(@booking, notice: "Booking added successfully")
    else
      render(:new, status: :unprocessable_entity)
    end
  end

  def show
  end

  private

  def set_flight
    @flight = Flight.find_by(id: params[:flight])

    unless @flight
      redirect_to(flights_path, alert: "Flight not found!")
    end
  end

  def booking_params
    params.expect(booking: [ :num_tickets, :flight, passengers_attributes: [ [ :email, :name ] ] ])
  end

  def set_booking
    @booking = Booking.find_by(id: params[:id])

    if @booking.nil?
      redirect_to(root_path, alert: "Booking not found!")
    end
  end
end

app/controllers/flights_controller.rb
# Handles all the logic needed to handle flights for users.
class FlightsController < ApplicationController
  def index
    @flights_count = Flight.count
    @airports = Airport.all.load

    @available_flights = available_flights

    @searched_query = {
      departure_airport: params[:departure_airport],
      arrival_airport: params[:arrival_airport],
      start: params[:start],
      num_tickets: params[:num_tickets]
    }
  end

  private

  # Retrieve all available flights based on the user's search query.
  def available_flights
    # Ensure all required parameters are present.
    unless [
      "start", "num_tickets", "departure_airport", "arrival_airport"
    ].all? { |key| params.key?(key) }
      return
    end

    arrival_airport = Airport.find_by(code: params[:arrival_airport])
    departure_airport = Airport.find_by(code: params[:departure_airport])

    if departure_airport == arrival_airport
      flash.now[:alert] = "Can't use the same airport as destination and arrival!"
    end

    Flight.includes(:departure_airport, :arrival_airport).where(
      departure_airport:,
      arrival_airport:,
      start: params[:start],
    ).load
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/new.html.erb
<div class="mb-4">
  <h1 class="text-2xl font-bold">Bookings</h1>
  <%= render "shared/searched_query", searched_query: @searched_query %>
</div>
<%= form_with model: @booking, class: "card" do |form| %>
  <div class="mb-4 card flex flex-col gap">
    <div class="gap-half">
      <%= form.label :flight, "Flight Code: #{@flight.details}" %>
      <%= form.text_field :flight,
                      id: @flight.id,
                      value: @flight.id,
                      readonly: true,
                      class: "input text-subtle" %>
    </div>
    <div>
      <%= form.label :num_tickers, "Number of Passengers" %>
      <%= form.text_field :num_tickets,
                      value: @searched_query[:num_tickets],
                      readonly: true,
                      class: "input text-subtle" %>
    </div>
  </div>
  <fieldset class="card mb-4">
    <legend class="text-xl font-medium">Passenger(s) Info</legend>
    <%= form.fields_for :passengers do |passenger| %>
      <div class="mb-4 card flex flex-col gap">
        <div>
          <%= passenger.label :name %>
          <%= passenger.text_field :name, class: "input", required: true %>
        </div>
        <div>
          <%= passenger.label :email %>
          <%= passenger.email_field :email, class: "input", required: true %>
        </div>
      </div>
    <% end %>
  </fieldset>
  <%= form.submit "Create Booking", class: "btn btn--primary" %>
<% end %>

app/views/bookings/show.html.erb
<h1 class="text-2xl font-bold">Booking Details</h1>
<div>
  <h3 class="text-xl font-semibold">ID:
    <%= @booking.id %></h3>
  <h3>Flight Details:
    <%= @booking.flights.last.details %></h3>
  <ul>
    <h3 class="text-xl font-semibold">Passengers:</h3>
    <% @booking.passengers.each do |passenger| %>
      <li class="mb-4 card">
        <p>Name:
          <%= passenger.name %></p>
        <p>Email:
          <%= passenger.email %></p>
      </li>
    <% end %>
  </ul>
</div>

app/views/flights/_available_flights_form.html.erb
<%= form_with url: new_booking_path, method: :get,
  class: "card flex flex-col gap",
  style: "inline-size: 350px" do |form| %>
  <input
    type="hidden"
    name="num_tickets"
    value="<%= @searched_query[:num_tickets] %>"
  >
    <div class="flex flex-col gap-half">
      <h1 class="text-2xl font-semibold leading-none">Available Flights</h1>
      <%= render "shared/searched_query", searched_query: @searched_query %>
    </div>
    <% if @available_flights.nil? || @available_flights.empty? %>
      <p>No available flights for this query.</p>
    <% else %>
      <% @available_flights.each do |flight| %>
        <div class="flex flex-col gap mb-2">
          <div class="flex gap">
            <div>
              <%= form.radio_button :flight, flight.id, required: true %>
            </div>
            <div>
              <%= form.label "flight_#{flight.id}", flight.details %>
              <p>Flight Number:
                <%= flight.number %></p>
              <p>Flight Duration:
                <%= flight.duration_in_hours %>
              </p>
            </div>
          </div>
        </div>
      <% end %>
      <%= form.submit "Book", class: "btn btn--primary" %>
    <% end %>
  <% end %>

app/views/flights/_form.html.erb
<%= form_with url: flights_path, method: :get, class: "card flex flex-col gap", style: "inline-size: 350px" do |form| %>
  <div class="flex flex-col gap-half">
    <h1 class="text-2xl font-semibold leading-none">Flight</h1>
    <p class="text-sm text-subtle">Number of flights:
      <%= @flights_count %>
    </p>
    <p class="text-sm text-subtle">Number of airports:
      <%= @airports.size %>
    </p>
  </div>
  <% if alert %>
    <p class="text-sm text-subtle" style="color: red;">
      <%= alert %>
    </p>
  <% end %>
  <div class="flex flex-col gap mb-2">
    <div class="flex flex-col gap-half">
      <%= form.label :departure_airport,
                 "Departure Airport: ",
                 class: "text-sm font-medium leading-none" %>
      <%= form.select :departure_airport,
                  @airports.map { |airport| [airport.code, airport.code] },
                  {},
                  class: "input" %>
    </div>
    <div class="flex flex-col gap-half">
      <%= form.label :arrival_airport,
                 "Arrival Airport: ",
                 class: "text-sm font-medium leading-none" %>
      <%= form.select :arrival_airport,
                  @airports.map { |airport| [airport.code, airport.code] },
                  {},
                  class: "input" %>
    </div>
    <div class="flex flex-col gap-half">
      <%= form.label :num_tickets,
                 "Number of Tickets: ",
                 class: "text-sm font-medium leading-none" %>
      <%= form.select :num_tickets, 1..4, {}, class: "input" %>
    </div>
    <div class="flex flex-col gap-half">
      <%= form.label :start,
                 "Flight Date (mm/dd/yyyy): ",
                 class: "text-sm font-medium leading-none" %>
      <%= form.date_field :start, class: "input", required: true %>
    </div>
  </div>
  <%= form.submit "Search", class: "btn btn--primary" %>
<% end %>

app/views/flights/index.html.erb
<div class="mb-8">
  <%= render "form", airports: @airports, flights: @flights %>
</div>
<div>
  <%= render "available_flights_form" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Odin Flight Booker" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= yield :head %>
    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :all, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body class="header-layout">
    <header id="header">
      <div class="container">
        <h1 class="font-bold text-2xl"><%= link_to "Odin Flight Booker", root_path %></h1>
      </div>
    </header>
    <main id="main">
      <div class="container">
        <%= yield %>
      </div>
    </main>
  </body>
</html>

app/views/shared/_searched_query.html.erb
<p class="text-subtle text-xl">
  Searched query:
  <ul>
    <li class="text-subtle text-sm">Departure Airport:
      <%= searched_query[:departure_airport] || "nil" %>
    </li>
    <li class="text-sm text-subtle">Arrival Airport:
      <%= searched_query[:arrival_airport] || "nil" %>
    </li>
    <li class="text-sm text-subtle">Number of Tickets:
      <%= searched_query[:num_tickets] || "nil" %>
    </li>
    <li class="text-sm text-subtle">Flight Date:
      <%= searched_query[:start] || "nil" %>
    </li>
  </ul>
</p>